### PR TITLE
Annotated injector

### PR DESCRIPTION
**Pull request by clkao**

### CODE REVIEW

**Comment by matteosuppo** [comment]
It should annotate itself with ng-min when launching gulp build. It should also be annotated in the minified version provided. Am I wrong?

**Comment by clkao** [comment]
Yes, sadly for many build pipelines, it grabs `main` files as defined in bower.json (which is also broken in this package, btw) and can do minify with tools other than ng-min :(

**Comment by matteosuppo** [comment]
Would it work if I defined the minified file angular-filereader.min.js as main in the bowr.json?

**Comment by matteosuppo** [comment]
Well, it can't hurt to have it already annotated, I guess

**Pull request merged**
